### PR TITLE
do-not-merge Add keynote speakers bio and images

### PR DESCRIPTION
**Pull request by contrepoint**
Keynote Speakers
* VJ Um Amel
* Lynn Cyrin

### CODE REVIEW

**Comment by jwise** [comment]
Can you mark this as do-not-merge in the PR title until we get our speakers to OK it?

Thanks,
joshua

**Comment by jwise** [comment]
Hmm, a few thoughts:

1) Do we want to try to balance the length of Lynn's bio with Laila's?  (Do we want to suggest edits to tell more about Lynn, or do we want to try to dial Laila's back some -- or neither?)

2) Did we decide whether we want to highlight Laila as Laila, or as VJ Um Amel?

**Comment by jeenalee** [comment]
I see that Lynn's bio is shorter than VJ Um Amel's, but I don't think it's so short that it feels really imbalanced. I think part of that is VJ Um Amel professor title is more than a line long.

Laila has most of her art work under VJ Um Amel (twitter, vimeo, instagram etc) so I think highlighting her VJ persona is probably what we want to do, in my opinion. I like how the bio does mention her academic position too.

**Comment by jwise** [comment]
merged as #21

**Pull request closed without merging**
